### ISSUE TITLE
Spurious warning "The leftSideBearing is greater than the advance width (unlikely value)"

### ISSUE THREAD

**Issue by StevanWhite** [HinTak/Font-Validator#55]
First, in the "details" field, it reports a "glyph #".  It would be much more helpful for font developers to report the font slot number.

The bug is, it complains about zero-width mark glyphs, such as Hebrew hataf segol.  If the Unicode data says the glyph is a nonspacing mark (Mn), I think the check should be different -- perhaps it should check that the advance width is 0.

**Comment by HinTak** [comment]
That's reasonable. I'll add the zero width check/ or perhaps checks its unicode range.

**Comment by HinTak** [comment]
Fixed in https://github.com/HinTak/Font-Validator/commit/69b4402dc783cfdffe5cf380244dd5e8cca61941 . Thanks for the report. 

As for the glyph id to name/charcode look up, I'd rather not add it - sometimes such info is missing (and requires cross referencing another table which could be broken also), plus the fact that glyph to charcode is not necessarily unique - the Google Noto /Adobe Source CJK fonts actually have a few hundreds glyphs mapping to multiple slots. Quite a few CJK glyph shapes have multiple meanings.  e.g. As standalone characters or radicals(= family roots for dictionary index entries), so occupies more than 1 slots.

Btw, there is an open bug of fontforge failing to load Google Noto / Adobe Source CJK, because of this. Fontforge treats the glyph as associated with the higher unicode value (of multiple), thus missing a few hundred characters at the lower more commonly-used end, when re-encoded.

**Comment by StevanWhite** [comment]
Just to be clear: 
I didn't mention charCode... by which I presume the character encoding of the glyph.
The font slot number for the glyph is not essentially related to the character encoding.
I don't know if it's hard to determine the glyph's slot number in the font from the glyph number.

**Comment by HinTak** [comment]
I don't really know what the slot number is, in this case. Can you tell me say, what's the slot number for some of the glyph id's in a specific version of FreeSerif for example? I have been using that (and my build of svn with current-ish fontforge) for most of my recent work in this area.

**Comment by StevanWhite** [comment]
Hi,

In FreeSerif, for example, you will find a glyph
named 'mal_ya.pstf'
slot# 59793
glyph# 8934
Unicode: -1

The slot number of a glyph *might* be the same as its character code, and
for Unicode fonts like FreeFont, glyphs for Unicode characters are usually
put in the corresponding slot, but a glyph with no encoding can also be in
a slot, and the charcode of the glyph in the slot does not necessarily
correspond to the slot number.

For me, and those of us using FontForge, the advantage of the slot number
is that it is much easier to find the glyph with that number.  (There is a
work-around, but it's clumsy and non-obvious and a little dangerous.)

Thanks!

**Comment by HinTak** [comment]
Argh, I think that's a feature specific/artificial/internal to fontforge - it basically assign glyphs to its encoded values, with work-in-progress (unencoded) glyphs taking up the upper side beyond the current max encoded glyph. You may find that, by putting an encoded value to a glyph, its slot number changes when you save/reload.

Basically it puts unused glyphs at the top after the others. Once you starts referring /naming /encoding a glyph, it moves...

**Comment by StevanWhite** [comment]
Ah.  I should have known.

FWIW, here's how you can sort out the glyph number in FontForge:  Under "Encoding" choose "Compact".  The glyphs will then appear according to glyph number -- and the "slot number" will be the same as the "glyph number".  BE CAREFUL not to save the font this way -- it can be difficult to get things back the way they were.

Correction: No, the slot number is pretty stable, so long as you don't change the encoding.  However, when a font is *generated*, the slot numbers of non-encoded glyphs is often changed (sometimes in objectionable ways.)

Another correction: un-encoded glyphs usually aren't "work-in-progress" glyphs.  They are deliberately used in several ways by production fonts.  FreeFont uses them primarily as glyph replacements for GSUB lookups, and as components for use in other glyphs as references.

**Comment by StevanWhite** [comment]
Still -- call it a request: sure show the glyph number.  But if a glyph name can be retrieved, please display that.  This would make FontVal much easier to use.
