### ISSUE TITLE
OS/2: "The version number is valid, but less than 5" [W2106]

### ISSUE THREAD

**Issue by anthrotype** [HinTak/Font-Validator#9]
I'd recommend to downgrade this warning message to informative status.
I think it's perfectly fine to have OS/2 table version less than the current one (version 5), as long as one does not attempt to use any of the flags which are only defined in subsequent versions of the table.

**Comment by HinTak** [comment]
I am okay with that. It got bumped up from v3 to v5 because Behdad's CBLC/CBDT font sample has a v4 OS/2 table . So the recent change basically means warning on every font I have, as I don't actually have a v5 sample. 

That said, it is the sort of issue that I think should be filed at the issue tracker with Microsoft as we need their input on this, about (1) how keen they are to push people to update fonts to latest spec, as well as (2) their plans on their internal version in this matter, and anticipating divergence between the two.

So I am closing this and either you or me can file at Microsoft and point back to this on my questions above.

**Comment by anthrotype** [comment]
ok, I'll open the same issue on MS repo then.
thanks
